# platform configurations

include ../../shared/preamble.cfg

export CC      := clang
export CXX     := clang++
export WINDRES := windres

%:
	@$(MAKE) --no-print-directory -C ../../shared $@
