# -*- mode: makefile-gmake -*-

# A general purpose Makefile-based build system

include preamble.cfg
include system.cfg
include toolchain.cfg
include paths.cfg
include flags.cfg
include modules.cfg
include rules.cfg
include build.cfg
